services:
  frontend:
    image: ghcr.io/marsvest/vl_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - vl_network

  backend:
    image: ghcr.io/marsvest/vl_backend:latest
    ports:
      - "8000:8000"
    networks:
      - vl_network
    environment:
      - DB_PASS=${DB_PASS}

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  vl_network:
    driver: bridge
