services:
  frontend:
    image: ghcr.io/marsvest/vl_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - vl_network

  backend:
    image: ghcr.io/marsvest/vl_backend:latest
    ports:
      - "8000:8000"
    networks:
      - vl_network

networks:
  vl_network:
    driver: bridge
